import Footer from "./components/Footer/Footer";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="font-poppins text-2xl xl:text-3xl">
				{children}
				<Footer />
			</body>
		</html>
	);
}
